Repository IT-Cotato/9th-Squadus-FE, pull requests merged in 2024-05, with the labels that each got.

#2 FEAT: kakao 에서 토큰 받아오기
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/screen/sign_in_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature

#4 Feature/#1 kakao login
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/screen/sign_in_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature

#6 Setting/kakao token
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/screen/sign_in_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ⚙ Setting

#8 feat: home ui 틀 구현
  assets/images/Group.png
  lib/main.dart
  lib/screen/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature

#11 fix: 충돌 해결 과정에서 실수 고침
  lib/screen/home_screen.dart
Labels: 🐞 BugFix

#12 feat: 구인글 컴포넌트 구현
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/component/recruitment_card_component.dart
  lib/main.dart
  lib/screen/home_screen.dart
  lib/screen/sign_in_screen.dart
  pubspec.lock
Labels: ✨ Feature

#13 feat: 주요공지 컴포넌트 구현
  lib/component/notice_card_component.dart
  lib/main.dart
  lib/screen/home_screen.dart
Labels: ✨ Feature
